"""
Django settings for HTPhuBinhSite project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$k3lczaw1s^a8#6-=nl*(6i!q9@m46od*g=(_9g=wz2fey1oaq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

TIME_ZONE = 'Asia/Ho_Chi_Minh   '
USE_L10N = False
DATE_INPUT_FORMATS = ['%m/%d/%y']
DATE_FORMATS = ['%m/%d/%y']

# START keyboard_shortcuts settings #
HOTKEYS = [
            {'keys': 'h',  # go home
            'link': '/',
             },
            {'keys': 'l',  # go home
            'link': '/thietlapnamhoc/viewChiaLop/',
             },
            {'keys': 'c+l',
            'link': '/thietlapnamhoc/detailLop/',
             },
            {'keys': 'n',  # go home
            'link': '/thietlapnamhoc/viewNienKhoa/',
             },
            {'keys': 'c+n',
            'link': '/thietlapnamhoc/detailNienKhoa/',
             },
            {'keys': 't',  # go home
            'link': '/vanhanhnamhoc/viewThieuNhi/',
             },
            {'keys': 'c+t',
            'link': '/vanhanhnamhoc/detailThieuNhi/',
             },
            {'keys': 'b',  # go home
            'link': '/vanhanhnamhoc/viewBangDiem/',
             },
            {'keys': 'd',  # go home
            'link': '/vanhanhnamhoc/viewDiemDanh/',
             },
        ]
SPECIAL_DISABLED = True
# END keyboard_shortcuts settings #

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ckeditor_uploader',
    'ckeditor',

    'keyboard_shortcuts',

    'Base.apps.BaseConfig',
    'ThietLapNamHocMoi.apps.ThietlapnamhocmoiConfig',
    'VanHanhNamHoc.apps.VanhanhnamhocConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HTPhuBinhSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'HTPhuBinh',
        'USER': 'root',
        'PASSWORD': '123123',
        'HOST': ''
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}
# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/Static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'Static/HomePage'),
]

AUTH_USER_MODEL = 'ThietLapNamHocMoi.HuynhTruong'
MEDIA_ROOT = '%s/Static/HomePage/Uploads/' %BASE_DIR
CKEDITOR_UPLOAD_PATH = '.'
ROOT_URLCONF = 'HTPhuBinhSite.urls'

