# Generated by Django 3.2.7 on 2021-10-01 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThietLapNamHocMoi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chialop',
            name='PhanCong_ChiaLop',
        ),
        migrations.RemoveField(
            model_name='danhmuclop',
            name='ChiaLop_Lop',
        ),
        migrations.RemoveField(
            model_name='danhmucnienkhoa',
            name='ChiaLop_NienKhoa',
        ),
        migrations.RemoveField(
            model_name='huynhtruong',
            name='PhanCong_HuynhTruong',
        ),
        migrations.AddField(
            model_name='chialop',
            name='DanhSachHuynhTruong',
            field=models.ManyToManyField(blank=True, related_name='DanhSachHuynhTruong', through='ThietLapNamHocMoi.PhanCong', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='danhmuclop',
            name='CacNienKhoaTungTaoLop',
            field=models.ManyToManyField(related_name='CacNienKhoaTungTaoLop', through='ThietLapNamHocMoi.ChiaLop', to='ThietLapNamHocMoi.DanhMucNienKhoa'),
        ),
        migrations.AddField(
            model_name='danhmucnienkhoa',
            name='CacLopTrongNienKhoa',
            field=models.ManyToManyField(related_name='CacLopTrongNienKhoa', through='ThietLapNamHocMoi.ChiaLop', to='ThietLapNamHocMoi.DanhMucLop'),
        ),
        migrations.AddField(
            model_name='huynhtruong',
            name='CacLopDaDay',
            field=models.ManyToManyField(related_name='CacLopDaDay', through='ThietLapNamHocMoi.PhanCong', to='ThietLapNamHocMoi.ChiaLop'),
        ),
    ]
