# Generated by Django 3.2.7 on 2021-10-03 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThietLapNamHocMoi', '0002_auto_20211001_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='BangDiem',
            fields=[
                ('Is_Active', models.IntegerField(choices=[(1, 'Đang sử dụng'), (0, 'Không còn sử dụng')], default=1)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('id_BangDiem', models.AutoField(primary_key=True, serialize=False)),
                ('DiemKTM_HK1', models.FloatField(null=True)),
                ('DiemKTV_HK1', models.FloatField(null=True)),
                ('DiemKT15_HK1', models.FloatField(null=True)),
                ('DiemKT1T_HK1', models.FloatField(null=True)),
                ('DiemThi_HK1', models.FloatField(null=True)),
                ('DiemKTM_HK2', models.FloatField(null=True)),
                ('DiemKTV_HK2', models.FloatField(null=True)),
                ('DiemKT15_HK2', models.FloatField(null=True)),
                ('DiemKT1T_HK2', models.FloatField(null=True)),
                ('DiemThi_HK2', models.FloatField(null=True)),
                ('ChiaLop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChiaLop_BangDiem', to='ThietLapNamHocMoi.chialop')),
            ],
            options={
                'db_table': 'table_BangDiem',
            },
        ),
        migrations.CreateModel(
            name='ThieuNhi',
            fields=[
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('id_ThieuNhi', models.AutoField(primary_key=True, serialize=False)),
                ('TenThanh', models.CharField(blank=True, default='', max_length=45)),
                ('HoTen', models.CharField(blank=True, default='', max_length=100)),
                ('NgaySinh', models.DateField(blank=True, null=True)),
                ('NgayRuaToi', models.DateField(blank=True, null=True)),
                ('TenThanhCha', models.CharField(blank=True, default='', max_length=45)),
                ('HoTenCha', models.CharField(blank=True, default='', max_length=100)),
                ('TenThanhMe', models.CharField(blank=True, default='', max_length=45)),
                ('HoTenMe', models.CharField(blank=True, default='', max_length=100)),
                ('DiaChi', models.CharField(blank=True, default='', max_length=100)),
                ('KhuDao', models.CharField(blank=True, default='', max_length=45)),
                ('Sdt1', models.CharField(blank=True, default='', max_length=15)),
                ('Sdt2', models.CharField(blank=True, default='', max_length=15)),
                ('Is_Active', models.IntegerField(choices=[(1, 'Đang học'), (0, 'Đang tạm nghỉ'), (-1, 'Đã nghỉ học')], default=1)),
                ('CacLopDaHoc', models.ManyToManyField(blank=True, related_name='CacLopDaHoc', through='ThietLapNamHocMoi.BangDiem', to='ThietLapNamHocMoi.ChiaLop')),
                ('Updated_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_ThieuNhi',
            },
        ),
        migrations.AddField(
            model_name='bangdiem',
            name='ThieuNhi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ThieuNhi', to='ThietLapNamHocMoi.thieunhi'),
        ),
        migrations.AddField(
            model_name='bangdiem',
            name='Updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chialop',
            name='BangDiemThieuNhi',
            field=models.ManyToManyField(blank=True, related_name='BangDiemThieuNhi', through='ThietLapNamHocMoi.BangDiem', to='ThietLapNamHocMoi.ThieuNhi'),
        ),
    ]
