# Generated by Django 3.2.7 on 2021-10-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThietLapNamHocMoi', '0004_auto_20211005_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diemdanh',
            name='KetQuaDiemDanh',
            field=models.CharField(choices=[('C', 'Có mặt'), ('P', 'Vắng có phép'), ('V', 'Vắng không phép')], max_length=1, null=True),
        ),
    ]
