# Generated by Django 3.2.7 on 2021-11-03 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThietLapNamHocMoi', '0006_cotdiem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemSo',
            fields=[
                ('Is_Active', models.IntegerField(choices=[(1, 'Đang sử dụng'), (0, 'Không còn sử dụng')], default=1)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('id_DiemSo', models.AutoField(primary_key=True, serialize=False)),
                ('id_CotDiem', models.IntegerField()),
                ('HocKy', models.IntegerField(choices=[(1, 'Học kỳ I'), (2, 'Học kỳ II')], default=1)),
                ('LoaiCotDiem', models.IntegerField(choices=[(0, 'Hệ số 01'), (1, "KT 15'"), (2, 'KT 1 Tiết'), (3, 'Thi Học kỳ')])),
                ('DiemSo', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('Is_KetSo', models.IntegerField(choices=[(1, 'Đã kết sổ'), (0, 'Chưa kết sổ')], default=0)),
            ],
            options={
                'db_table': 'table_DiemSo',
            },
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKT15_HK1',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKT15_HK2',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKT1T_HK1',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKT1T_HK2',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKTM_HK1',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKTM_HK2',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKTV_HK1',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemKTV_HK2',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemThi_HK1',
        ),
        migrations.RemoveField(
            model_name='bangdiem',
            name='DiemThi_HK2',
        ),
        migrations.DeleteModel(
            name='CotDiem',
        ),
        migrations.AddField(
            model_name='diemso',
            name='BangDiem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BangDiem_CotDiem', to='ThietLapNamHocMoi.bangdiem'),
        ),
        migrations.AddField(
            model_name='diemso',
            name='Updated_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
